---
- name: Add NGINX Ingress Helm repository
  command: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
  changed_when: false
  tags: nginx-ingress

- name: Update Helm repositories
  command: helm repo update
  changed_when: false
  tags: nginx-ingress

- name: Install NGINX Ingress Controller
  command: >
    helm install ingress-nginx ingress-nginx/ingress-nginx
    --namespace ingress-nginx
    --create-namespace
  register: nginx_install
  changed_when: nginx_install.rc == 0
  failed_when: nginx_install.rc != 0 and "already exists" not in nginx_install.stderr
  tags: nginx-ingress

- name: Wait for NGINX Ingress Controller to be ready
  command: >
    kubectl wait --namespace ingress-nginx
    --for=condition=ready pod
    --selector=app.kubernetes.io/component=controller
    --timeout=120s
  register: wait_result
  retries: 30
  delay: 10
  until: wait_result.rc == 0
  tags: nginx-ingress