---
- name: Add NGINX Ingress Helm repository
  command: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
  changed_when: false

- name: Update Helm repositories
  command: helm repo update
  changed_when: false

- name: Install NGINX Ingress Controller
  command: >
    helm install ingress-nginx ingress-nginx/ingress-nginx
    --namespace ingress-nginx
    --create-namespace
    --set controller.publishService.enabled=true
  register: nginx_install
  changed_when: nginx_install.rc == 0
  failed_when: nginx_install.rc != 0 and "already exists" not in nginx_install.stderr 