---
- name: Include dependencies tasks
  ansible.builtin.import_tasks: dependencies.yml

- name: Include master tasks
  ansible.builtin.import_tasks: master.yml
  when: inventory_hostname in groups['master']

- name: Include worker tasks
  ansible.builtin.import_tasks: worker.yml
  when: inventory_hostname in groups['worker']
