---
- name: Wait for master node to be reachable
  ansible.builtin.wait_for:
    host: "{{ hostvars['master1']['ansible_default_ipv4']['address'] }}"
    port: 6443
    timeout: 300
    delay: 10
  when: inventory_hostname in groups['worker']

- name: Get join command from master
  ansible.builtin.shell: kubeadm token create --print-join-command
  delegate_to: "{{ groups['master'][0] }}"
  register: join_command
  when: inventory_hostname in groups['worker']

- name: Join the cluster
  ansible.builtin.shell: "{{ join_command.stdout }}"
  when: inventory_hostname in groups['worker'] and join_command.stdout is defined