---
- name: Configure all nodes
  hosts: all
  become: true
  roles:
    - common

- name: Configure Kubernetes master nodes
  hosts: master
  become: true
  roles:
    - kubernetes

- name: Configure Kubernetes worker nodes
  hosts: worker
  become: true
  roles:
    - kubernetes

- name: Install Helm on master nodes
  hosts: master
  become: true
  roles:
    - helm

- name: Install NGINX Ingress and ArgoCD on master nodes
  hosts: master
  become: true
  roles:
    - nginx-ingress
    - argocd