---
- name: Add ArgoCD Helm repository
  command: helm repo add argo https://argoproj.github.io/argo-helm
  changed_when: false

- name: Update Helm repositories
  command: helm repo update
  changed_when: false

- name: Install ArgoCD
  command: >
    helm install argocd argo/argo-cd
    --namespace argocd
    --create-namespace
    --set server.extraArgs="{--insecure}"
    --set server.service.type=LoadBalancer
  register: argocd_install
  changed_when: argocd_install.rc == 0
  failed_when: argocd_install.rc != 0 and "already exists" not in argocd_install.stderr

- name: Wait for ArgoCD server to be ready
  command: kubectl wait --for=condition=available --timeout=300s deployment/argocd-server -n argocd
  register: wait_result
  retries: 30
  delay: 10
  until: wait_result.rc == 0 